id: IDE93843F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:59:06+00:00'
last_modified: '2022-06-07T17:19:41.854155+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG016
  title: རྗེ་རིན་པོ་ཆེ་མཉམ་མེད་ཤེས་རབ་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5F6A:
      image_group_id: I1KG5096
      title: ''
      total_pages: 172
      order: 1
      base_file: 5F6A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
