id: P003066
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG016
  title: རྗེ་རིན་པོ་ཆེ་མཉམ་མེད་ཤེས་རབ་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    4361328e56c64737ae9e1f67358ccd20:
      image_group_id: I1KG5096
      title: ''
      volume_number: 1
      total_pages: 172
