id: P003066
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG016
  title: རྗེ་རིན་པོ་ཆེ་མཉམ་མེད་ཤེས་རབ་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    4361328e56c64737ae9e1f67358ccd20:
      image_group_id: I1KG5096
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
